### ISSUE TITLE
Display doesn't work after upload factory example

### ISSUE THREAD

**Issue by zebox** [Xinyuan-LilyGO/T-Dongle-ESP32S2#3]
I bought `LILYGO T-Dongle ESP32-S2` with `ST7789V` LCD. It started and show data on LCD properly (out of box) before I had upload `factory` example (with `Arduion IDE 2.0.4`).  After example uploaded LCD doesn't show anything. Firmware upload and wrote successful. 

```text
esptool.py v4.5.1
Serial port COM30
Connecting.....
Chip is ESP32-S2 (revision v0.0)
Features: WiFi, No Embedded Flash, No Embedded PSRAM, ADC and temperature sensor calibration in BLK2 of efuse V1
Crystal is 40MHz
MAC: 34:b4:72:6c:47:c8
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Erasing flash (this may take a while)...
Chip erase completed successfully in 2.0s
Compressed 14656 bytes to 10171...
Writing at 0x00001000... (20 %)
Writing at 0x00001c5d... (40 %)
Writing at 0x000027ad... (60 %)
Writing at 0x000032ca... (80 %)
Writing at 0x00003c93... (100 %)
Wrote 14656 bytes (10171 compressed) at 0x00001000 in 0.1 seconds (effective 1820.4 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 146...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (146 compressed) at 0x00008000 in 0.0 seconds (effective 3031.3 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...
Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 4237.6 kbit/s)...
Hash of data verified.
Compressed 896592 bytes to 545861...
Writing at 0x00010000... (0 %)
Writing at 0x0001148d... (0 %)
Writing at 0x00012231... (1 %)
Writing at 0x00018290... (1 %)
Writing at 0x00019cc6... (1 %)
Writing at 0x0001ba4a... (2 %)
Writing at 0x000224f0... (2 %)
....
....
....
Writing at 0x000e9c20... (99 %)
Writing at 0x000ea7e3... (100 %)
Wrote 896592 bytes (545861 compressed) at 0x00010000 in 3.7 seconds (effective 1921.9 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```

I added debug print to `loop` for watch in Serial monitor. 

Serial monitor output my debug print:
```text
scan done
ping... // my debug print 
ping...
ping...
ping...
ping...
....
```
ESP32 connects to my WIFI network correctly too. But LCD doesn't work :(

There is my source of `pin_config.h`

```c
// pin_config.h
#pragma once

/********************************* USE TFT_eSPI Lib ************************************/
#define ST7789_DRIVER    // Configure all registers
#define TFT_WIDTH  135
#define TFT_HEIGHT 240
#define CGRAM_OFFSET      // Library will add offsets required
#define LOAD_GLCD   // Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
#define LOAD_FONT2  // Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters
#define LOAD_FONT4  // Font 4. Medium 26 pixel high font, needs ~5848 bytes in FLASH, 96 characters
#define LOAD_FONT6  // Font 6. Large 48 pixel font, needs ~2666 bytes in FLASH, only characters 1234567890:-.apm
#define LOAD_FONT7  // Font 7. 7 segment 48 pixel font, needs ~2438 bytes in FLASH, only characters 1234567890:.
#define LOAD_FONT8  // Font 8. Large 75 pixel font needs ~3256 bytes in FLASH, only characters 1234567890:-.
#define LOAD_GFXFF  // FreeFonts. Include access to the 48 Adafruit_GFX free fonts FF1 to FF48 and custom fonts

#define SMOOTH_FONT
#define SPI_FREQUENCY  40000000
#define SPI_READ_FREQUENCY  20000000
#define SPI_TOUCH_FREQUENCY  2500000

#define TFT_MISO 4
#define TFT_MOSI 35
#define TFT_SCLK 36
#define TFT_CS 34  // Chip select control pin
#define TFT_DC 37  // Data Command control pin
#define TFT_RST 38 // Reset pin (could connect to RST pin)

#define TFT_BL 33

#define SD_PIN_NUM_MISO 13
#define SD_PIN_NUM_MOSI 11
#define SD_PIN_NUM_CLK 12
#define SD_PIN_NUM_CS 10

#define LED_PIN 39

#define IIC_SDA 44
#define IIC_SCL 43
```

Other source files the same as in example [factory](https://github.com/Xinyuan-LilyGO/T-Dongle-ESP32S2/tree/main/example/factory)

How can I solve my issue?

**Comment by lewisxhe** [comment]
1. I uploaded the test [firmware](https://github.com/Xinyuan-LilyGO/T-Dongle-ESP32S2/tree/main/firmware), and you can swipe it in to see if the hardware is good

3. Recopy [TFT_eSPI](https://github.com/Xinyuan-LilyGO/T-Dongle-ESP32S2/tree/main/lib/TFT_eSPI) to the libraries directory. When opening the arduino ide, do not click Update Library, otherwise the configured file will be overwritten

**Comment by Jorge-Blanco-813** [comment]
this not working for me, if I upload bin file it works, but still no screen with Arduino code

**Comment by lewisxhe** [comment]
If you click Update Library, the TFT will be overwritten_ The default configuration for eSPI is the display header file, which cannot be avoided unless you use Arduino IDE version 2.0 or later

**Comment by zebox** [comment]
@lewisxhe 
The LCD on the device revived after recopy [TFT_eSPI](https://github.com/Xinyuan-LilyGO/T-Dongle-ESP32S2/tree/main/lib/TFT_eSPI) without update it in Arduino IDE. After that i uploaded factory example sketch. The LCD displays data and all work correctly. 

Also i didn't can upload firmware with you tool. Tool works strange, after press start button it try sync (I waited over 2 hours and process didn't stop). I try stop and start again process doesn't start again. Log output `case ok` (only app restart allow execute command again). It not important because recopy  `TFT_eSPI` solved my issue. 

Thank you!

**Comment by lewisxhe** [comment]
This is a very painful issue. Since Arduino 2.0 updated the update library functionality, there have been a lot of such issues, and 2.0 can easily get stuck in the compilation step. Therefore, I recommend that you use version 1.18.19.

**Comment by Jorge-Blanco-813** [comment]
do not agree, please fix the code, this example was written in properly there's no reason that the update of the library should overwrite the files with the display settings
